CREATE TABLE t_user(

  id BIGINT NOT NULL AUTO_INCREMENT,

  name VARCHAR(50) DEFAULT NULL COMMENT '姓名',

  phone VARCHAR(50) DEFAULT NULL COMMENT '手机号',

  email VARCHAR(60) DEFAULT NULL COMMENT '邮箱',

  status INT COMMENT '用户状态',

  password VARCHAR(60) DEFAULT NULL COMMENT '密码',

  imgsrc VARCHAR(80) DEFAULT NULL COMMENT '头像链接',

  PRIMARY KEY (id)

)DEFAULT CHARSET = utf8;


CREATE TABLE t_story(

  id BIGINT NOT NULL AUTO_INCREMENT,

  iconsrc VARCHAR(60) COMMENT 'icon图片的地址',

  title VARCHAR(300) DEFAULT NULL COMMENT '故事标题',

  create_time VARCHAR(60) COMMENT '创建时间',

  imgsrc VARCHAR(80) DEFAULT NULL COMMENT '标题页图片',

  content LONGTEXT COMMENT '故事内容',

  PRIMARY KEY (id)

) DEFAULT CHARSET = utf8;

