CREATE TABLE t_user(

  id BIGINT NOT NULL AUTO_INCREMENT,

  name VARCHAR(50) DEFAULT NULL COMMENT '姓名',

  phone VARCHAR(50) DEFAULT NULL COMMENT '手机号',

  email VARCHAR(60) DEFAULT NULL COMMENT '邮箱',

  wechat VARCHAR(50) DEFAULT NULL COMMENT '微信号',

  password VARCHAR(60) DEFAULT NULL COMMENT '密码',

  imgsrc VARCHAR(80) DEFAULT NULL COMMENT '头像链接',

  PRIMARY KEY (id)

)DEFAULT CHARSET = utf8;

